## EXAMPLE YOUTUBE - LIBRARY SK-LEARN

In [78]:
import numpy as np
import pandas as pd

In [79]:
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn import metrics, neighbors
from sklearn import preprocessing

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [80]:
# IMPORT DATA FROM CSV FILE
data = pd.read_csv('car.data')
data.shape # dimensions of the dataframe 

(1727, 7)

In [81]:
# Takes dataframe, and convert it into a CSV file and add header
data.to_csv("car.data", header=['buying','mant','doors','persons','lug_boot','safety','class'], index=False)

data = pd.read_csv('car.data') #Overwrites the dataframe data
data.head(10) #display the firts 10 attributes


buying   mant doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc
5  vhigh  vhigh     2       2      big    low  unacc
6  vhigh  vhigh     2       2      big    med  unacc
7  vhigh  vhigh     2       2      big   high  unacc
8  vhigh  vhigh     2       4    small    low  unacc
9  vhigh  vhigh     2       4    small    med  unacc

In [82]:
#Selecting attributes

X = data[[
    'buying',
    'mant',
    'safety'
]].values

y = data[['class']]
#print(X,y)



In [119]:
#Converting data (strings --> integers)
Le = preprocessing.LabelEncoder()
for i in range(len(X[0])):                    
    X[:,i] = Le.fit_transform(X[:,i])

#display new features values    
print(X)

#Another alternative to conver data (mapping)
label_map = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}

y['class'] = y['class'].map(label_map)


[[3 3 2]
 [3 3 0]
 [3 3 1]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


<ipython-input-119-2f77907b6e41>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class'] = y['class'].map(label_map)


In [122]:
#Convert into a numpy array
y = np.array(y)
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [2],
       [3]])

## Create model 

Nearest neighbors

In [144]:
#Choose the model
knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')
# Split the traingin set and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

#knn.fit(X_train, y_train)  
knn.fit(X_train, y_train.ravel()) 

#Prediction 
pred = knn.predict(X_test)
accuracy = metrics.accuracy_score(y_test, pred)
accuracy


0.7341040462427746

In [134]:
y_test.shape
y_train.shape

(346, 1)

In [135]:
X_test.shape
X_train.shape

(1381, 3)

In [139]:
y_train.ravel()

array([0, 0, 1, ..., 0, 2, 0])